version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ingressos
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  cache:
    image: redis

  app:
    build:
      context: ./api
    depends_on:
      - db
      - cache
    ports:
      - "8080:8080"